### ISSUE TITLE
Unattachable block

### ISSUE THREAD

**Issue by anujk14** [Ensembl/XML-To-Blockly#10]
The problem occurs if a ref contains a magic node, and it is called in the following way:
1) First it is called from a non-magic parent like <element>
2) Then, it is called by a magic parent, i.e., a <oneOrMore>/<choice> etc.
If we reverse the order, the problem goes away.
Example to check the bug: bug_07_unattachable_block_for_oneOrMore_ref.rng

**Comment by ens-lg4** [comment]
Fixed with commit e7e18d38eedc75cdfd34bb15c15a89a2ba3591a6 ,
but it looks like other bugs were re-surrected as a result, so infinite loop detection suffered.

**Comment by sgiorgetti** [comment]
Closing the issue, as about to archive this repo
