### ISSUE TITLE
Incorrect name in ehive_pipeline_schema2.rng

### ISSUE THREAD

**Issue by anujk14** [Ensembl/XML-To-Blockly#8]
The block that is created for "template" (block 22 in current version) has a field called "template|" as its notch label. However, this notch accepts  block_8:hash , block_9:array and block_10:10 as its children. The name "template|" for such a notch is incorrect.

**Comment by muffato** [comment]
This also seems to be solved, but let's keep the ticket open until we've understood everything

**Comment by muffato** [comment]
Fixed
