### ISSUE TITLE
Incorrect name in for repeated magic block 

### ISSUE THREAD

**Issue by anujk14** [Ensembl/XML-To-Blockly#9]
A choice/interleave that has a one/zeroOrMore as its child gets assigned the block number as part of its notch label and childrenInfo list. If this one/zeroOrMore turns out to be a repeated child for which a block has already been created, we get an incorrect notch label as well as childrenInfo list (since currently childrenInfo uses pretty names) . 

Example to test bug : bug_05_choice_having_oneOrMore_having_wrong_name.rng

**Comment by muffato** [comment]
This is fixed on the version Leo's has just pushed, but let's keep the ticket open until we've checked all the examples and ensured there are no regressions

**Comment by muffato** [comment]
Fixed
